openapi: 3.0.1

info:
  title: Sample API
  description: This API allows users to retrieve and create data related to products.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /products:
    get:
      summary: Retrieve all products
      operationId: getProducts
      responses:
        '200':
          description: Successful retrieval of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    
    post:
      summary: Create a new product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the product
        name:
          type: string
          description: Name of the product
        price:
          type: number
          format: float
          description: Price of the product
        quantity:
          type: integer
          description: Quantity in stock
      required:
        - name
        - price
        - quantity

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

security:
  - ApiKeyAuth: []